query GetQuizzes(
  $skip: Float
  $take: Float
  $where: QuizWhereInput
  $orderBy: QuizOrderByWithRelationInput
) {
  GetQuizzes(skip: $skip, take: $take, where: $where, orderBy: $orderBy) {
    id
    title
    link
    userId
    description
    timeLimit
    deadline
    publishedAt
    enableFeedback

    createdAt
    updatedAt
    deletedAt
  }
}

query GetQuiz($where: QuizWhereUniqueInput!) {
  GetQuiz(where: $where) {
    id
    title
    link
    userId
    description
    timeLimit
    deadline
    publishedAt
    enableFeedback

    createdAt
    updatedAt
    deletedAt
  }
}

mutation DeleteQuiz($id: String!) {
  DeleteQuiz(id: $id) {
    id
    title
    link
    userId
    description
    timeLimit
    deadline
    publishedAt
    enableFeedback

    createdAt
    updatedAt
    deletedAt
  }
}

mutation UpdateQuiz($id: String!, $data: QuizUpdateInput!) {
  UpdateQuiz(id: $id, data: $data) {
    id
    title
    link
    userId
    description
    timeLimit
    deadline
    publishedAt
    enableFeedback

    createdAt
    updatedAt
    deletedAt
  }
}

mutation CreateQuiz($data: CreateQuizInput!) {
  CreateQuiz(data: $data) {
    id
    title
    link
    userId
    description
    timeLimit
    deadline
    publishedAt
    enableFeedback

    createdAt
    updatedAt
    deletedAt
  }
}

query VerifyQuizLink($link: String!) {
  VerifyQuizLink(link: $link) {
    id
    title
    # link
    # userId
    description
    # timeLimit
    # deadline
    # publishedAt
    # enableFeedback

    # createdAt
    # updatedAt
    # deletedAt
  }
}
